apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeloop.operatorName" . }}-crd
  labels:
    {{- include "kubeloop.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
data:
  trafficbinding-crd.yaml: |
{{ .Files.Get "crds/traffic.kubeloop.io_trafficbindings.yaml" | indent 4 }}
