{{- if and .Values.podDisruptionBudget.controller.enabled (eq .Values.controller.storage.type "postgresql") (gt (int .Values.controller.replicas) 1) }}
{{- if or (lt (int .Values.podDisruptionBudget.controller.minAvailable) 1) (ge (int .Values.podDisruptionBudget.controller.minAvailable) (int .Values.controller.replicas) ) }}
{{- fail "podDisruptionBudget.controller.minAvailable must be at least 1 and lower than controller.replicas" }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubeloop.controllerName" . }}
  labels:
    {{- include "kubeloop.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  minAvailable: {{ .Values.podDisruptionBudget.controller.minAvailable }}
  selector:
    matchLabels:
      {{- include "kubeloop.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
{{- end }}
