{{- if .Values.controlPlane.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeloop.controlPlaneServiceAccountName" . }}
  labels:
    {{- include "kubeloop.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
automountServiceAccountToken: true
---
{{- end }}
{{- if .Values.dataPlane.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeloop.dataPlaneServiceAccountName" . }}
  labels:
    {{- include "kubeloop.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-plane
automountServiceAccountToken: false
{{- end }}
{{- if .Values.operator.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeloop.operatorServiceAccountName" . }}
  labels:
    {{- include "kubeloop.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
automountServiceAccountToken: true
{{- end }}
