{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeloop.controllerServiceAccountName" . }}
  labels:
    {{- include "kubeloop.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
automountServiceAccountToken: true
---
{{- end }}
{{- if .Values.dataPlane.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeloop.dataPlaneServiceAccountName" . }}
  labels:
    {{- include "kubeloop.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-plane
automountServiceAccountToken: false
{{- end }}
{{- if .Values.operator.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeloop.operatorServiceAccountName" . }}
  labels:
    {{- include "kubeloop.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
automountServiceAccountToken: true
{{- end }}
