---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traffic.kubeloop.io
  resources:
  - trafficbindings
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traffic.kubeloop.io
  resources:
  - trafficbindings/finalizers
  verbs:
  - update
- apiGroups:
  - traffic.kubeloop.io
  resources:
  - trafficbindings/status
  verbs:
  - get
  - patch
  - update
