//go:build e2e && linux

package platform

import (
	"os"
	"strings"
	"testing"
)

func assertPlatformE2EDNS(t *testing.T, want bool) {
	t.Helper()
	content, err := os.ReadFile("/etc/systemd/resolved.conf.d/90-kubeloop.conf")
	got := err == nil &&
		strings.Contains(string(content), "# Generated by KubeLoop") &&
		strings.Contains(string(content), platformE2EDomain)
	if got != want {
		t.Fatalf("Linux DNS configured=%v want %v (read error=%v)", got, want, err)
	}
}
