//go:build e2e && darwin

package platform

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func assertPlatformE2EDNS(t *testing.T, want bool) {
	t.Helper()
	content, err := os.ReadFile(filepath.Join("/etc/resolver", platformE2EDomain))
	got := err == nil && strings.Contains(string(content), "# Generated by KubeLoop")
	if got != want {
		t.Fatalf("macOS resolver configured=%v want %v (read error=%v)", got, want, err)
	}
}
