//go:build darwin

package platform

import (
	"encoding/json"
	"fmt"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/fengqi-dev/kube-loop/internal/singbox"
)

const (
	resolverDir        = "/etc/resolver"
	dnsMarker          = "# Generated by KubeLoop"
	searchBackupFile   = "search-domains.bak.json"
	noSearchDomainText = "Search Domains set"
)

type searchBackup map[string][]string

func ApplyLinkDNS(string, singbox.DNSMeta) error { return nil }
func RestoreLinkDNS(string) error                { return nil }

func ApplyDNS(workDir string, dns singbox.DNSMeta) error {
	if err := sweepResolvers(); err != nil {
		return err
	}
	if err := os.MkdirAll(resolverDir, 0o755); err != nil {
		return err
	}
	searchLine := strings.Join(dns.Search, " ")
	for _, domain := range dns.Domains {
		if !safeResolverName(domain) {
			return fmt.Errorf("unsafe resolver domain %q", domain)
		}
		content := fmt.Sprintf(
			"%s\nnameserver %s\nport %d\nsearch %s\noptions ndots:%d\n",
			dnsMarker, dns.Listen, dns.Port, searchLine, dns.Ndots,
		)
		path := filepath.Join(resolverDir, domain)
		if existing, err := os.ReadFile(path); err == nil &&
			!strings.Contains(string(existing), dnsMarker) {
			return fmt.Errorf("resolver file %s is not owned by KubeLoop", path)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return err
		}
	}
	services, err := activeNetworkServices()
	if err != nil {
		return err
	}
	backup := make(searchBackup, len(services))
	for _, service := range services {
		backup[service] = getSearchDomains(service)
	}
	content, err := json.Marshal(backup)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(workDir, searchBackupFile), content, 0o600); err != nil {
		return err
	}
	for _, service := range services {
		merged := appendUnique(append([]string{}, dns.Search...), backup[service]...)
		args := append([]string{"-setsearchdomains", service}, merged...)
		if len(merged) == 0 {
			args = append(args, "Empty")
		}
		_ = exec.Command("/usr/sbin/networksetup", args...).Run()
	}
	flushDarwinDNS()
	return nil
}

func RestoreDNS(workDir string, _ singbox.DNSMeta) error {
	var firstErr error
	if err := sweepResolvers(); err != nil {
		firstErr = err
	}
	content, err := os.ReadFile(filepath.Join(workDir, searchBackupFile))
	if err == nil {
		var backup searchBackup
		if json.Unmarshal(content, &backup) == nil {
			for service, domains := range backup {
				args := []string{"-setsearchdomains", service}
				if len(domains) == 0 {
					args = append(args, "Empty")
				} else {
					args = append(args, domains...)
				}
				if runErr := exec.Command("/usr/sbin/networksetup", args...).Run(); runErr != nil && firstErr == nil {
					firstErr = runErr
				}
			}
		}
		_ = os.Remove(filepath.Join(workDir, searchBackupFile))
	}
	flushDarwinDNS()
	return firstErr
}

func sweepResolvers() error {
	entries, err := os.ReadDir(resolverDir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.Type()&os.ModeSymlink != 0 || !entry.Type().IsRegular() {
			continue
		}
		path := filepath.Join(resolverDir, entry.Name())
		content, readErr := os.ReadFile(path)
		if readErr == nil && strings.Contains(string(content), dnsMarker) {
			if removeErr := os.Remove(path); removeErr != nil {
				return removeErr
			}
		}
	}
	return nil
}

func activeNetworkServices() ([]string, error) {
	output, err := exec.Command("/usr/sbin/networksetup", "-listallnetworkservices").Output()
	if err != nil {
		return nil, err
	}
	lines := strings.Split(strings.TrimSpace(string(output)), "\n")
	services := make([]string, 0, len(lines))
	for index, raw := range lines {
		service := strings.TrimSpace(raw)
		if index == 0 || service == "" || strings.HasPrefix(service, "*") {
			continue
		}
		info, infoErr := exec.Command("/usr/sbin/networksetup", "-getinfo", service).Output()
		if infoErr == nil && strings.Contains(string(info), "IP address:") {
			services = append(services, service)
		}
	}
	return services, nil
}

func getSearchDomains(service string) []string {
	output, err := exec.Command("/usr/sbin/networksetup", "-getsearchdomains", service).Output()
	if err != nil || strings.Contains(string(output), noSearchDomainText) {
		return nil
	}
	return strings.Fields(string(output))
}

func appendUnique(values []string, extra ...string) []string {
	seen := make(map[string]struct{}, len(values)+len(extra))
	out := make([]string, 0, len(values)+len(extra))
	for _, value := range append(values, extra...) {
		if value == "" {
			continue
		}
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

func safeResolverName(value string) bool {
	return value != "" && value != "." && value != ".." &&
		filepath.Base(value) == value && !strings.ContainsAny(value, `/\`)
}

func flushDarwinDNS() {
	_ = exec.Command("/usr/bin/dscacheutil", "-flushcache").Run()
	_ = exec.Command("/usr/bin/killall", "-HUP", "mDNSResponder").Run()
}

func CleanupRoutes(routes []string) {
	for _, raw := range routes {
		prefix, err := netip.ParsePrefix(raw)
		if err != nil {
			continue
		}
		prefix = prefix.Masked()
		if prefix.Bits() == prefix.Addr().BitLen() {
			_ = exec.Command("/sbin/route", "-n", "delete", "-host", prefix.Addr().String()).Run()
		} else {
			_ = exec.Command("/sbin/route", "-n", "delete", "-net", prefix.String()).Run()
		}
	}
}
