// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKubeconfig() {
  return window['go']['app']['App']['AddKubeconfig']();
}

export function AddKubeconfigPath(arg1) {
  return window['go']['app']['App']['AddKubeconfigPath'](arg1);
}

export function Bootstrap() {
  return window['go']['app']['App']['Bootstrap']();
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function Connect(arg1, arg2) {
  return window['go']['app']['App']['Connect'](arg1, arg2);
}

export function ConnectMode(arg1, arg2, arg3) {
  return window['go']['app']['App']['ConnectMode'](arg1, arg2, arg3);
}

export function DisablePodSSH(arg1) {
  return window['go']['app']['App']['DisablePodSSH'](arg1);
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function EnablePodSSH(arg1) {
  return window['go']['app']['App']['EnablePodSSH'](arg1);
}

export function GatewayInstallManifest() {
  return window['go']['app']['App']['GatewayInstallManifest']();
}

export function GetHostAliases(arg1) {
  return window['go']['app']['App']['GetHostAliases'](arg1);
}

export function GetMCPStatus() {
  return window['go']['app']['App']['GetMCPStatus']();
}

export function GetManualNetwork(arg1) {
  return window['go']['app']['App']['GetManualNetwork'](arg1);
}

export function GetSingBoxConfig() {
  return window['go']['app']['App']['GetSingBoxConfig']();
}

export function HelperStatus() {
  return window['go']['app']['App']['HelperStatus']();
}

export function InstallHelper() {
  return window['go']['app']['App']['InstallHelper']();
}

export function InstallMCPClient(arg1) {
  return window['go']['app']['App']['InstallMCPClient'](arg1);
}

export function ListIntercepts() {
  return window['go']['app']['App']['ListIntercepts']();
}

export function ListMirrors() {
  return window['go']['app']['App']['ListMirrors']();
}

export function ListPodSSH() {
  return window['go']['app']['App']['ListPodSSH']();
}

export function ListPods(arg1, arg2) {
  return window['go']['app']['App']['ListPods'](arg1, arg2);
}

export function ListPortForwards() {
  return window['go']['app']['App']['ListPortForwards']();
}

export function ListPreviews() {
  return window['go']['app']['App']['ListPreviews']();
}

export function ListServices(arg1, arg2) {
  return window['go']['app']['App']['ListServices'](arg1, arg2);
}

export function Namespaces(arg1) {
  return window['go']['app']['App']['Namespaces'](arg1);
}

export function OpenUpdatePage() {
  return window['go']['app']['App']['OpenUpdatePage']();
}

export function ProbeContext(arg1) {
  return window['go']['app']['App']['ProbeContext'](arg1);
}

export function RegenerateMCPToken() {
  return window['go']['app']['App']['RegenerateMCPToken']();
}

export function ReloadContexts() {
  return window['go']['app']['App']['ReloadContexts']();
}

export function RememberSelection(arg1, arg2) {
  return window['go']['app']['App']['RememberSelection'](arg1, arg2);
}

export function RemoveKubeconfig(arg1) {
  return window['go']['app']['App']['RemoveKubeconfig'](arg1);
}

export function ResetSessions() {
  return window['go']['app']['App']['ResetSessions']();
}

export function SessionIntentCounts() {
  return window['go']['app']['App']['SessionIntentCounts']();
}

export function SetDNSNamespace(arg1, arg2) {
  return window['go']['app']['App']['SetDNSNamespace'](arg1, arg2);
}

export function SetHostAliases(arg1, arg2) {
  return window['go']['app']['App']['SetHostAliases'](arg1, arg2);
}

export function SetMCPEnabled(arg1) {
  return window['go']['app']['App']['SetMCPEnabled'](arg1);
}

export function SetMCPPort(arg1) {
  return window['go']['app']['App']['SetMCPPort'](arg1);
}

export function SetMCPTokenEnabled(arg1) {
  return window['go']['app']['App']['SetMCPTokenEnabled'](arg1);
}

export function SetManualNetwork(arg1, arg2) {
  return window['go']['app']['App']['SetManualNetwork'](arg1, arg2);
}

export function StartIntercept(arg1) {
  return window['go']['app']['App']['StartIntercept'](arg1);
}

export function StartMirror(arg1) {
  return window['go']['app']['App']['StartMirror'](arg1);
}

export function StartPortForward(arg1) {
  return window['go']['app']['App']['StartPortForward'](arg1);
}

export function StartPreview(arg1) {
  return window['go']['app']['App']['StartPreview'](arg1);
}

export function StopIntercept(arg1) {
  return window['go']['app']['App']['StopIntercept'](arg1);
}

export function StopPortForward(arg1) {
  return window['go']['app']['App']['StopPortForward'](arg1);
}

export function StopPreview(arg1) {
  return window['go']['app']['App']['StopPreview'](arg1);
}

export function TestIntercept(arg1) {
  return window['go']['app']['App']['TestIntercept'](arg1);
}

export function TestPortForward(arg1) {
  return window['go']['app']['App']['TestPortForward'](arg1);
}

export function UninstallHelper() {
  return window['go']['app']['App']['UninstallHelper']();
}
