// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {update} from '../models';
import {dataplane} from '../models';
import {remote} from '../models';
import {profile} from '../models';
import {mcp} from '../models';
import {helper} from '../models';
import {exchange} from '../models';
import {filetransfer} from '../models';
import {mirror} from '../models';
import {podssh} from '../models';
import {portforward} from '../models';
import {preview} from '../models';
import {singbox} from '../models';
import {discovery} from '../models';

export function Bootstrap():Promise<app.BootstrapData>;

export function CancelServerFileTransfer(arg1:string,arg2:string):Promise<void>;

export function CancelServerLogin():Promise<void>;

export function CheckForUpdates():Promise<update.Info>;

export function ClearServerFileTransferHistory(arg1:string):Promise<void>;

export function ConnectServerDataPlane(arg1:string,arg2:string):Promise<dataplane.Status>;

export function CreateServerLocalFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateServerPodFile(arg1:app.ServerPodFileCreateRequest):Promise<remote.PodFileTask>;

export function DeleteServerLocalFile(arg1:string):Promise<void>;

export function DeleteServerPodFile(arg1:app.ServerPodFileDeleteRequest):Promise<remote.PodFileTask>;

export function DeleteServerProfile(arg1:string):Promise<profile.State>;

export function DisconnectServerDataPlane(arg1:string):Promise<dataplane.Status>;

export function GetMCPStatus():Promise<mcp.Status>;

export function GetServerNetworkSettings(arg1:string):Promise<app.ServerNetworkSettings>;

export function GetServerSingBoxConfig(arg1:string):Promise<string>;

export function HelperStatus():Promise<helper.Status>;

export function InstallHelper():Promise<void>;

export function InstallMCPClient(arg1:string):Promise<mcp.InstallResult>;

export function ListServerExchanges(arg1:string):Promise<Array<exchange.Info>>;

export function ListServerFileTransfers(arg1:string):Promise<Array<filetransfer.Task>>;

export function ListServerLocalFiles(arg1:string):Promise<Array<app.ServerLocalFileEntry>>;

export function ListServerMirrors(arg1:string):Promise<Array<mirror.Info>>;

export function ListServerPodFiles(arg1:app.ServerPodFileTarget):Promise<remote.PodFileList>;

export function ListServerPodSSH(arg1:string):Promise<Array<podssh.Info>>;

export function ListServerPortForwards(arg1:string):Promise<Array<portforward.Info>>;

export function ListServerPreviews(arg1:string):Promise<Array<preview.Info>>;

export function LoadServerInventory(arg1:string,arg2:string):Promise<app.RemoteInventory>;

export function LoginServerOIDC(arg1:string,arg2:string):Promise<app.AuthSession>;

export function LogoutServer(arg1:string):Promise<void>;

export function OpenServerPodSSH(arg1:string,arg2:string):Promise<void>;

export function OpenUpdatePage():Promise<void>;

export function PickServerDownloadPath(arg1:string,arg2:string):Promise<string>;

export function PickServerUploadPath(arg1:string):Promise<string>;

export function RefreshServerLogin(arg1:string):Promise<app.AuthSession>;

export function RegenerateMCPToken():Promise<string>;

export function RenameServerLocalFile(arg1:string,arg2:string):Promise<void>;

export function RenameServerPodFile(arg1:app.ServerPodFileRenameRequest):Promise<remote.PodFileTask>;

export function ResizeServerExec(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function ResumeServerFileTransfer(arg1:string,arg2:string):Promise<filetransfer.Task>;

export function SaveServerProfile(arg1:app.SaveServerProfileRequest):Promise<app.ServerProfileResult>;

export function SelectServerProfile(arg1:string):Promise<profile.State>;

export function ServerAuthStatus(arg1:string):Promise<app.AuthSession>;

export function ServerDataPlaneLogs(arg1:string):Promise<Array<string>>;

export function ServerDataPlaneMetrics(arg1:string):Promise<singbox.Metrics>;

export function ServerLocalHomeDirectory():Promise<string>;

export function ServerProfiles():Promise<profile.State>;

export function SetMCPEnabled(arg1:boolean):Promise<void>;

export function SetMCPPort(arg1:number):Promise<void>;

export function SetMCPTokenEnabled(arg1:boolean):Promise<void>;

export function SetServerDNSNamespace(arg1:string,arg2:string):Promise<app.ServerNetworkSettings>;

export function SetServerHostAliases(arg1:string,arg2:Array<profile.HostAlias>):Promise<app.ServerNetworkSettings>;

export function SetServerSOCKSPort(arg1:string,arg2:number):Promise<app.ServerNetworkSettings>;

export function StartServerExchange(arg1:exchange.Request):Promise<exchange.Info>;

export function StartServerExec(arg1:app.ServerExecRequest):Promise<remote.ExecTask>;

export function StartServerFileTransfer(arg1:filetransfer.Request):Promise<filetransfer.Task>;

export function StartServerMirror(arg1:mirror.Request):Promise<mirror.Info>;

export function StartServerPodSSH(arg1:app.ServerPodSSHRequest):Promise<podssh.Info>;

export function StartServerPortForward(arg1:portforward.Request):Promise<portforward.Info>;

export function StartServerPreview(arg1:preview.Request):Promise<preview.Info>;

export function StartServerTunnel(arg1:string):Promise<dataplane.Status>;

export function StopServerExchange(arg1:string,arg2:string):Promise<void>;

export function StopServerExec(arg1:string,arg2:string):Promise<void>;

export function StopServerMirror(arg1:string,arg2:string):Promise<void>;

export function StopServerPodSSH(arg1:string,arg2:string):Promise<void>;

export function StopServerPortForward(arg1:string,arg2:string):Promise<void>;

export function StopServerPreview(arg1:string,arg2:string):Promise<void>;

export function StopServerTunnel(arg1:string):Promise<dataplane.Status>;

export function TestServerAddress(arg1:string):Promise<discovery.Document>;

export function TestServerDataPlane(arg1:string):Promise<void>;

export function TestServerPortForward(arg1:string,arg2:string):Promise<void>;

export function UninstallHelper():Promise<void>;

export function WriteServerExecInput(arg1:string,arg2:string,arg3:string):Promise<void>;
