// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['app']['App']['Bootstrap']();
}

export function CancelServerFileTransfer(arg1, arg2) {
  return window['go']['app']['App']['CancelServerFileTransfer'](arg1, arg2);
}

export function CancelServerLogin() {
  return window['go']['app']['App']['CancelServerLogin']();
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function ClearServerFileTransferHistory(arg1) {
  return window['go']['app']['App']['ClearServerFileTransferHistory'](arg1);
}

export function ConnectServerDataPlane(arg1, arg2) {
  return window['go']['app']['App']['ConnectServerDataPlane'](arg1, arg2);
}

export function CreateServerLocalFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateServerLocalFile'](arg1, arg2, arg3);
}

export function CreateServerPodFile(arg1) {
  return window['go']['app']['App']['CreateServerPodFile'](arg1);
}

export function DeleteServerLocalFile(arg1) {
  return window['go']['app']['App']['DeleteServerLocalFile'](arg1);
}

export function DeleteServerPodFile(arg1) {
  return window['go']['app']['App']['DeleteServerPodFile'](arg1);
}

export function DeleteServerProfile(arg1) {
  return window['go']['app']['App']['DeleteServerProfile'](arg1);
}

export function DisconnectServerDataPlane(arg1) {
  return window['go']['app']['App']['DisconnectServerDataPlane'](arg1);
}

export function GetMCPStatus() {
  return window['go']['app']['App']['GetMCPStatus']();
}

export function GetServerNetworkSettings(arg1) {
  return window['go']['app']['App']['GetServerNetworkSettings'](arg1);
}

export function GetServerSingBoxConfig(arg1) {
  return window['go']['app']['App']['GetServerSingBoxConfig'](arg1);
}

export function GetTrafficInspectionSettings() {
  return window['go']['app']['App']['GetTrafficInspectionSettings']();
}

export function HandleAuthCallbackURL(arg1) {
  return window['go']['app']['App']['HandleAuthCallbackURL'](arg1);
}

export function HelperStatus() {
  return window['go']['app']['App']['HelperStatus']();
}

export function ImportTrafficInspectionProtoDirectory() {
  return window['go']['app']['App']['ImportTrafficInspectionProtoDirectory']();
}

export function InstallHelper() {
  return window['go']['app']['App']['InstallHelper']();
}

export function InstallMCPClient(arg1) {
  return window['go']['app']['App']['InstallMCPClient'](arg1);
}

export function ListServerExchanges(arg1) {
  return window['go']['app']['App']['ListServerExchanges'](arg1);
}

export function ListServerFileTransfers(arg1) {
  return window['go']['app']['App']['ListServerFileTransfers'](arg1);
}

export function ListServerLocalFiles(arg1) {
  return window['go']['app']['App']['ListServerLocalFiles'](arg1);
}

export function ListServerMirrors(arg1) {
  return window['go']['app']['App']['ListServerMirrors'](arg1);
}

export function ListServerPodFiles(arg1) {
  return window['go']['app']['App']['ListServerPodFiles'](arg1);
}

export function ListServerPodSSH(arg1) {
  return window['go']['app']['App']['ListServerPodSSH'](arg1);
}

export function ListServerPortForwards(arg1) {
  return window['go']['app']['App']['ListServerPortForwards'](arg1);
}

export function ListServerPreviews(arg1) {
  return window['go']['app']['App']['ListServerPreviews'](arg1);
}

export function LoadServerInventory(arg1, arg2) {
  return window['go']['app']['App']['LoadServerInventory'](arg1, arg2);
}

export function LoginServerOIDC(arg1, arg2) {
  return window['go']['app']['App']['LoginServerOIDC'](arg1, arg2);
}

export function LogoutServer(arg1) {
  return window['go']['app']['App']['LogoutServer'](arg1);
}

export function OpenServerPodSSH(arg1, arg2) {
  return window['go']['app']['App']['OpenServerPodSSH'](arg1, arg2);
}

export function OpenUpdatePage() {
  return window['go']['app']['App']['OpenUpdatePage']();
}

export function PickServerDownloadPath(arg1, arg2) {
  return window['go']['app']['App']['PickServerDownloadPath'](arg1, arg2);
}

export function PickServerUploadPath(arg1) {
  return window['go']['app']['App']['PickServerUploadPath'](arg1);
}

export function RefreshServerLogin(arg1) {
  return window['go']['app']['App']['RefreshServerLogin'](arg1);
}

export function RegenerateMCPToken() {
  return window['go']['app']['App']['RegenerateMCPToken']();
}

export function RenameServerLocalFile(arg1, arg2) {
  return window['go']['app']['App']['RenameServerLocalFile'](arg1, arg2);
}

export function RenameServerPodFile(arg1) {
  return window['go']['app']['App']['RenameServerPodFile'](arg1);
}

export function ResizeServerExec(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ResizeServerExec'](arg1, arg2, arg3, arg4);
}

export function ResumeServerFileTransfer(arg1, arg2) {
  return window['go']['app']['App']['ResumeServerFileTransfer'](arg1, arg2);
}

export function SaveServerProfile(arg1) {
  return window['go']['app']['App']['SaveServerProfile'](arg1);
}

export function SelectServerProfile(arg1) {
  return window['go']['app']['App']['SelectServerProfile'](arg1);
}

export function ServerAuthStatus(arg1) {
  return window['go']['app']['App']['ServerAuthStatus'](arg1);
}

export function ServerDataPlaneLogs(arg1) {
  return window['go']['app']['App']['ServerDataPlaneLogs'](arg1);
}

export function ServerDataPlaneMetrics(arg1) {
  return window['go']['app']['App']['ServerDataPlaneMetrics'](arg1);
}

export function ServerLocalHomeDirectory() {
  return window['go']['app']['App']['ServerLocalHomeDirectory']();
}

export function ServerProfiles() {
  return window['go']['app']['App']['ServerProfiles']();
}

export function SetMCPEnabled(arg1) {
  return window['go']['app']['App']['SetMCPEnabled'](arg1);
}

export function SetMCPPort(arg1) {
  return window['go']['app']['App']['SetMCPPort'](arg1);
}

export function SetMCPTokenEnabled(arg1) {
  return window['go']['app']['App']['SetMCPTokenEnabled'](arg1);
}

export function SetServerDNSNamespace(arg1, arg2) {
  return window['go']['app']['App']['SetServerDNSNamespace'](arg1, arg2);
}

export function SetServerHostAliases(arg1, arg2) {
  return window['go']['app']['App']['SetServerHostAliases'](arg1, arg2);
}

export function SetServerSOCKSPort(arg1, arg2) {
  return window['go']['app']['App']['SetServerSOCKSPort'](arg1, arg2);
}

export function SetTrafficInspectionEnabled(arg1) {
  return window['go']['app']['App']['SetTrafficInspectionEnabled'](arg1);
}

export function StartServerExchange(arg1) {
  return window['go']['app']['App']['StartServerExchange'](arg1);
}

export function StartServerExec(arg1) {
  return window['go']['app']['App']['StartServerExec'](arg1);
}

export function StartServerFileTransfer(arg1) {
  return window['go']['app']['App']['StartServerFileTransfer'](arg1);
}

export function StartServerMirror(arg1) {
  return window['go']['app']['App']['StartServerMirror'](arg1);
}

export function StartServerPodSSH(arg1) {
  return window['go']['app']['App']['StartServerPodSSH'](arg1);
}

export function StartServerPortForward(arg1) {
  return window['go']['app']['App']['StartServerPortForward'](arg1);
}

export function StartServerPreview(arg1) {
  return window['go']['app']['App']['StartServerPreview'](arg1);
}

export function StartServerTunnel(arg1) {
  return window['go']['app']['App']['StartServerTunnel'](arg1);
}

export function StopServerExchange(arg1, arg2) {
  return window['go']['app']['App']['StopServerExchange'](arg1, arg2);
}

export function StopServerExec(arg1, arg2) {
  return window['go']['app']['App']['StopServerExec'](arg1, arg2);
}

export function StopServerMirror(arg1, arg2) {
  return window['go']['app']['App']['StopServerMirror'](arg1, arg2);
}

export function StopServerPodSSH(arg1, arg2) {
  return window['go']['app']['App']['StopServerPodSSH'](arg1, arg2);
}

export function StopServerPortForward(arg1, arg2) {
  return window['go']['app']['App']['StopServerPortForward'](arg1, arg2);
}

export function StopServerPreview(arg1, arg2) {
  return window['go']['app']['App']['StopServerPreview'](arg1, arg2);
}

export function StopServerTunnel(arg1) {
  return window['go']['app']['App']['StopServerTunnel'](arg1);
}

export function TestServerAddress(arg1) {
  return window['go']['app']['App']['TestServerAddress'](arg1);
}

export function TrafficInspectionEvents(arg1) {
  return window['go']['app']['App']['TrafficInspectionEvents'](arg1);
}

export function UninstallHelper() {
  return window['go']['app']['App']['UninstallHelper']();
}

export function WriteServerExecInput(arg1, arg2, arg3) {
  return window['go']['app']['App']['WriteServerExecInput'](arg1, arg2, arg3);
}
