apiVersion: v2
name: kubeloop
description: KubeLoop control plane and independently scalable tunnel data plane
type: application
version: 2.0.0-rc.2
appVersion: "v2.0.0-rc.2"
kubeVersion: ">=1.25.0-0"
home: https://github.com/fengqi-dev/kube-loop
sources:
  - https://github.com/fengqi-dev/kube-loop
